name: Test and Build

on:
  push:
    branches:
      - main
    
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # setting environment
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Test the code
      - name: Run Pytest tests
        run: |
          pytest tests/test_app.py

      - name: Docker Credentials
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ env.VERSION }}

      # Push the Docker Image
      - name: Push the Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ env.VERSION }}