name: CI/CD - Test Calculator App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: |
        python -m venv venv
        source venv/bin/activate
        pip install fastapi[all] pytest

    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest tests/test_app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa


    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'

          if [ ! -d "Devlopment" ]; then
            git clone https://github.com/shahriar0999/AutoCalc.git Devlopment
          else
            cd Devlopment
            git reset --hard
            git pull origin main
          fi

          sudo apt update
          sudo apt upgrade

          cd Devlopment

          git pull origin main

          pip install --upgrade pip
          pip install -r requirements.txt


          pkill -f "python main.py" || true

          nohup python main.py  > fastapi.log 2>&1 &

        EOF
        

